services:
    flight:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        environment:
            docker: "true"
        ports:
            - "8080:80"
        depends_on:
            - postgres
        volumes:
            - ./public/uploads:/var/www/html/public/uploads

    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: mp-wd-0326
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: post
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./database/script.sql:/docker-entrypoint-initdb.d/01-schema.sql
            - ./database/data.sql:/docker-entrypoint-initdb.d/02-data.sql

volumes:
    pgdata:
